name: fab_circular_menu_plus
description: A Flutter package to create a nice circular menu using a Floating Action Button.
homepage: https://github.com/CsabaConsulting/fab_circular_menu_plus
version: 0.0.3

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  analyzer: ^7.2.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
